# --- Django SECRET_KEY: generated by Terraform, stored encrypted in SSM ---
# Special characters limited to a shell/env-file safe set.
resource "random_password" "django_secret_key" {
  length           = 64
  special          = true
  override_special = "-_=+@#%"
}

resource "aws_ssm_parameter" "django_secret_key" {
  # checkov:skip=CKV_AWS_337:encrypted with the AWS managed aws/ssm KMS key; a customer-managed key is not required in a single-account lab
  name        = "/${var.project_name}/django/secret_key"
  description = "Django SECRET_KEY for dpaste (read by EC2 at deploy time)"
  type        = "SecureString"
  value       = random_password.django_secret_key.result

  tags = {
    Name = "${var.project_name}-django-secret-key"
  }
}
